[package]
name = "coreutils_jpo"
license = "MIT"
version = "0.4.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = ""
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
