[package]
name = "coreutils_json"
license = "MIT"
version = "0.5.1"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "Json service."
edition = "2018"

[dependencies]
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"